version: "3.7"

services:
  db:
    image: db
    container_name: find-collectors
    build: 
      context: ./find-collectors/db-scripts
      target: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    volumes:
      - ./find-collectors-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped