BEGIN;
CREATE TABLE IF NOT EXISTS estado(
    id SERIAL PRIMARY KEY,
    uf VARCHAR(2) NOT NULL UNIQUE,
    nome_estado VARCHAR(100) NOT NULL
);
 
CREATE TABLE IF NOT EXISTS municipio(
    id SERIAL PRIMARY KEY,
    cidade VARCHAR(100) NOT NULL,
    estado_id INTEGER NOT NULL REFERENCES estado(id) ON UPDATE CASCADE ON DELETE NO ACTION,
    UNIQUE(cidade, estado_id) 
);

CREATE TABLE IF NOT EXISTS pessoa(
    id SERIAL PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    senha VARCHAR(100),
    telefone VARCHAR(15),
    cep VARCHAR(10),
    endereco VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    municipio_id INTEGER NOT NULL REFERENCES municipio(id) ON UPDATE CASCADE ON DELETE NO ACTION
);
CREATE TABLE IF NOT EXISTS reciclador(
    id SERIAL PRIMARY KEY,
    pessoa_id INTEGER NOT NULL REFERENCES pessoa(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS catador(
    id SERIAL PRIMARY KEY,
    tipo VARCHAR (100),
    descricao TEXT,
    pessoa_id INTEGER NOT NULL REFERENCES pessoa(id) ON UPDATE CASCADE ON DELETE NO ACTION,
    padrinho_id INTEGER NOT NULL REFERENCES reciclador(id) ON UPDATE CASCADE ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS coleta(
    id SERIAL PRIMARY KEY,
    data_e_hora TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    local VARCHAR(100) NOT NULL,
    tipo_de_lixo VARCHAR(100) NOT NULL,
    catador_id INTEGER NOT NULL REFERENCES catador(id) ON UPDATE CASCADE ON DELETE NO ACTION,
    reciclador_id INTEGER NOT NULL REFERENCES reciclador(id) ON UPDATE CASCADE ON DELETE NO ACTION
);


CREATE TABLE IF NOT EXISTS ponto_coleta(
    id SERIAL PRIMARY KEY,
    horario_funcionamento TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    cep VARCHAR(10),
    endereco VARCHAR(100) NOT NULL,
    bairro VARCHAR(100) NOT NULL,
    numero VARCHAR(10) NOT NULL,
    municipio_id INTEGER NOT NULL REFERENCES municipio(id) ON UPDATE CASCADE ON DELETE NO ACTION,
    UNIQUE(endereco, bairro, numero, municipio_id)
);

COMMIT;
