server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/find-collectors
spring.datasource.username=postgres
spring.datasource.password=postgres
jpa.hibernate.ddl-auto=validate
flyway.enabled=true
flyway.locations=classpath:db/migration
springdoc.packagesToScan=br.fai.findcollectors.findcollectorsapi