package br.fai.findcollectors.exceptions;

public enum ErrorCode {

    BUSINESS_RULE_VIOLATION,
    PERSON_NOT_FOUND,
    COLLECT_NOT_FOUND,
    RECYCLER_NOT_FOUND,
    EMAIL_ALREADY_REGISTERED,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    AUTHENTICATION_REQUIRED,
    AUTHENTICATION_UNAVAILABLE,
    ACCESS_DENIED,
    COLLECT_NOT_AVAILABLE
}
