<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>

	<groupId>br.fai.find-collectors</groupId>
	<artifactId>find-collectors</artifactId>
	<name>find-collectors</name>
	<description>Um projeto de estudo voltado para ajudar catadores de lixo reciclável.</description>
	<version>0.0.1-SNAPSHOT</version>

	<modules>
		<module>find-collectors-api</module>
		<module>find-collectors-client</module>
		<module>find-collectors-database</module>
		<module>find-collectors-model</module>
	</modules>

	<packaging>pom</packaging>

	<properties>
		<maven.compiler.source>8</maven.compiler.source>
		<maven.compiler.target>8</maven.compiler.target>
	</properties>

	<dependencyManagement>
		<dependencies>
			<!--Dependencias internas do projeto-->
			<dependency>
				<groupId>br.fai.find-collectors</groupId>
				<artifactId>find-collectors-model</artifactId>
				<version>0.0.1-SNAPSHOT</version>
			</dependency>

			<dependency>
				<groupId>br.fai.find-collectors</groupId>
				<artifactId>find-collectors-database</artifactId>
				<version>0.0.1-SNAPSHOT</version>
			</dependency>

			<!--Dependencias externas do projeto-->
			<dependency>
				<groupId>org.springframework</groupId>
				<artifactId>spring-context</artifactId>
				<version>5.3.22</version>
			</dependency>

			<dependency>
				<groupId>org.postgresql</groupId>
				<artifactId>postgresql</artifactId>
				<version>42.2.5</version>
			</dependency>

			<dependency>
				<groupId>org.springdoc</groupId>
				<artifactId>springdoc-openapi-ui</artifactId>
				<version>1.6.9</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

</project>
